# Generated by Django 5.2.6 on 2026-04-22 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especie', models.CharField(choices=[('Canino', 'Canino'), ('Felino', 'Felino'), ('Ave', 'Ave'), ('Reptil', 'Reptil'), ('Roedor', 'Roedor'), ('Pez', 'Pez'), ('Otros', 'Otros')], max_length=20, verbose_name='Especie')),
                ('raza', models.CharField(blank=True, default='', max_length=100, verbose_name='Raza')),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascotas_mascota',
                'ordering': ['nombre'],
            },
        ),
    ]
