# Generated by Django 5.2.6 on 2026-04-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='alergias',
            field=models.TextField(default='Ninguna', verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(default=False, verbose_name='Esterilizado'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto'),
        ),
    ]
