# Generated by Django 5.2.6 on 2026-04-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascota_alergias_mascota_esterilizado_mascota_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='alergias',
            field=models.TextField(blank=True, default='Ninguna', verbose_name='Alergias'),
        ),
    ]
