# Generated by Django 5.2.6 on 2026-04-23 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('Atendida', 'Atendida'), ('Cancelada', 'Cancelada')], default='Programada', max_length=20, verbose_name='Estado')),
                ('motivo_cancelacion', models.TextField(blank=True, default='', verbose_name='Motivo de cancelación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='agenda.disponibilidad', verbose_name='Disponibilidad')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='mascotas.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'agenda_cita',
                'ordering': ['disponibilidad__fecha', 'disponibilidad__hora_inicio'],
            },
        ),
    ]
