# Generated by Django 5.2.6 on 2026-04-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Motivo de consulta'),
        ),
    ]
