# Generated by Django 5.2.6 on 2026-04-27 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('consulta', 'Consulta'), ('cirugia', 'Cirugía'), ('estetica', 'Estética y peluquería'), ('vacunacion', 'Vacunación'), ('laboratorio', 'Laboratorio'), ('imagenes', 'Imágenes diagnósticas'), ('hospitalizacion', 'Hospitalización'), ('otro', 'Otro')], default='consulta', max_length=20, verbose_name='Categoría')),
                ('tarifa', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa')),
                ('duracion_minutos', models.PositiveIntegerField(default=30, verbose_name='Duración (minutos)')),
                ('esta_activo', models.BooleanField(default=True, help_text='Soft delete. Desactivar en lugar de eliminar.', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios_servicio',
                'ordering': ['nombre'],
            },
        ),
    ]
