# Generated by Django 5.2.6 on 2026-04-27 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='La tarifa no puede ser negativa.')], verbose_name='Tarifa'),
        ),
    ]
