# Generated by Django 5.2.6 on 2026-04-27 23:31

import django.core.validators
import django.db.models.deletion
import entregas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_alter_producto_options_producto_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('direccion_entrega', models.CharField(max_length=200, verbose_name='Dirección de entrega')),
                ('telefono_contacto', models.CharField(max_length=15, verbose_name='Teléfono de contacto')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Instrucciones especiales')),
                ('incidente_notas', models.TextField(blank=True, default='', verbose_name='Notas de incidente')),
                ('incidente_fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del incidente')),
                ('foto_evidencia', models.ImageField(blank=True, default='', help_text='Foto del paquete entregado. Máximo 5MB.', upload_to=entregas.models.evidencia_upload_path, verbose_name='Foto de evidencia')),
                ('firma_imagen', models.ImageField(blank=True, default='', help_text='Imagen de la firma del cliente. Máximo 5MB.', upload_to=entregas.models.firma_upload_path, verbose_name='Firma del cliente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('cliente', models.ForeignKey(limit_choices_to={'rol__nombre': 'Cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_como_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('domiciliario', models.ForeignKey(limit_choices_to={'rol__nombre': 'Domiciliario'}, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_como_domiciliario', to=settings.AUTH_USER_MODEL, verbose_name='Domiciliario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'entregas_pedido',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='La cantidad debe ser al menos 1.')], verbose_name='Cantidad')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='entregas.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_items', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item del pedido',
                'verbose_name_plural': 'Items del pedido',
                'db_table': 'entregas_pedidoitem',
            },
        ),
    ]
