# Generated by Django 5.2.6 on 2026-05-01 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='domiciliario',
            field=models.ForeignKey(blank=True, help_text='Se asigna automáticamente al crear el pedido, o el Admin puede reasignarlo después.', limit_choices_to={'rol__nombre': 'Domiciliario'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_como_domiciliario', to=settings.AUTH_USER_MODEL, verbose_name='Domiciliario'),
        ),
    ]
