# Generated by Django 5.2.6 on 2026-05-04 21:05

import entregas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_pedido_domiciliario_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='firma_imagen',
            field=models.ImageField(help_text='Imagen de la firma del cliente. Obligatorio. Máximo 5MB.', upload_to=entregas.models.firma_upload_path, verbose_name='Firma del cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='foto_evidencia',
            field=models.ImageField(help_text='Foto del paquete entregado. Obligatorio. Máximo 5MB.', upload_to=entregas.models.evidencia_upload_path, verbose_name='Foto de evidencia'),
        ),
    ]
