# Generated by Django 5.2.6 on 2026-04-22 02:20

from django.db import migrations, models


def seed_roles(apps, schema_editor):
    """Seed the 4 default roles using get_or_create for idempotency."""
    Rol = apps.get_model('usuarios', 'Rol')
    roles = [
        ('Cliente', 'Dueño de mascota'),
        ('Veterinario', 'Personal médico veterinario'),
        ('Domiciliario', 'Encargado de entregas a domicilio'),
        ('Administrador', 'Administrador del sistema'),
    ]
    for nombre, descripcion in roles:
        Rol.objects.get_or_create(nombre=nombre, defaults={'descripcion': descripcion})


def reverse_seed_roles(apps, schema_editor):
    """Reverse: remove seeded roles."""
    Rol = apps.get_model('usuarios', 'Rol')
    Rol.objects.filter(nombre__in=['Cliente', 'Veterinario', 'Domiciliario', 'Administrador']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'usuarios_rol',
            },
        ),
        migrations.RunPython(seed_roles, reverse_seed_roles),
    ]
