# Generated by Django 5.2.6 on 2026-04-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_rol_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Cédula'),
        ),
    ]
