# Generated by Django 5.2.6 on 2026-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Huellitas Alegres', max_length=200, verbose_name='Nombre de la clínica')),
                ('nit', models.CharField(default='901.234.567-8', max_length=50, verbose_name='NIT')),
                ('direccion', models.CharField(default='Calle 10 # 25-30, Bogotá', max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(default='601-555-0123', max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(default='info@huellitasalegres.com', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Configuración de Clínica',
                'verbose_name_plural': 'Configuración de Clínica',
                'db_table': 'usuarios_configuracionclinica',
            },
        ),
    ]
