# Generated by Django 5.2.6 on 2026-04-24 20:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('vacunas', 'Vacunas'), ('medicamentos', 'Medicamentos'), ('alimentos', 'Alimentos'), ('insumos', 'Insumos médicos'), ('higiene', 'Higiene y cuidado'), ('servicios', 'Servicios'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Soft delete. Desactivar en lugar de eliminar.', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=10, help_text='Umbral de alerta.stock ≤ stock_minimo*1.5 = amarillo, stock = 0 = rojo.', validators=[django.core.validators.MinValueValidator(0, message='El stock mínimo no puede ser negativo.')], verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_stock',
            field=models.IntegerField(default=0, help_text='Puede ser negativo para registrar inconsistencias.', verbose_name='Cantidad en stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10, verbose_name='Tipo de movimiento')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='La cantidad debe ser al menos 1.')], verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('motivo', models.CharField(blank=True, default='', max_length=200, verbose_name='Motivo')),
                ('historial_clinico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='historial.historialclinico', verbose_name='Historial clínico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'db_table': 'productos_movimientoinventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
