# Generated by Django 5.2.6 on 2026-05-06 22:24

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_proveedor_fk_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto de referencia del producto. Opcional.', null=True, upload_to=productos.models.producto_imagen_upload_path, verbose_name='Imagen del producto'),
        ),
    ]
