# Generated by Django 5.2.6 on 2026-04-24 02:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0003_cita_motivo'),
        ('mascotas', '0003_alergias_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.CharField(choices=[('consulta', 'Consulta general'), ('vacunacion', 'Vacunación'), ('cirugia', 'Cirugía'), ('urgencia', 'Urgencia'), ('control', 'Control'), ('laboratorio', 'Laboratorio')], default='consulta', max_length=20, verbose_name='Tipo de consulta')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de consulta')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, default='', verbose_name='Tratamiento')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='El peso debe ser mayor a 0 kg.'), django.core.validators.MaxValueValidator(999.99, message='El peso máximo es 999.99 kg.')], verbose_name='Peso (kg)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(34.0, message='La temperatura mínima es 34.0 °C.'), django.core.validators.MaxValueValidator(43.0, message='La temperatura máxima es 43.0 °C.')], verbose_name='Temperatura (°C)')),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40, message='La frecuencia cardíaca mínima es 40 lpm.'), django.core.validators.MaxValueValidator(300, message='La frecuencia cardíaca máxima es 300 lpm.')], verbose_name='Frecuencia cardíaca (lpm)')),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5, message='La frecuencia respiratoria mínima es 5 rpm.'), django.core.validators.MaxValueValidator(60, message='La frecuencia respiratoria máxima es 60 rpm.')], verbose_name='Frecuencia respiratoria (rpm)')),
                ('vacuna_aplicada', models.CharField(blank=True, default='', max_length=100, verbose_name='Vacuna aplicada')),
                ('proxima_vacunacion', models.DateField(blank=True, null=True, verbose_name='Próxima vacunación')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de consulta')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='agenda.cita', verbose_name='Cita')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales', to='mascotas.mascota', verbose_name='Mascota')),
                ('veterinario', models.ForeignKey(limit_choices_to={'rol__nombre': 'Veterinario'}, on_delete=django.db.models.deletion.PROTECT, related_name='historiales', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Historial Clínico',
                'verbose_name_plural': 'Historiales Clínicos',
                'db_table': 'historial_historialclinico',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
