# Generated by Django 5.2.6 on 2026-04-24 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
        ('productos', '0002_alter_producto_options_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='producto_aplicado',
            field=models.ForeignKey(blank=True, help_text='Producto del inventario utilizado en esta consulta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_clinicos', to='productos.producto', verbose_name='Producto aplicado'),
        ),
    ]
