# Generated by Django 5.2.6 on 2026-04-24 22:41

import django.db.models.deletion
import historial.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_historialclinico_producto_aplicado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=historial.models.adjunto_upload_path, verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('radiografia', 'Radiografía'), ('laboratorio', 'Laboratorio'), ('foto', 'Fotografía'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de archivo')),
                ('descripcion', models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('historial_clinico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='historial.historialclinico', verbose_name='Historial clínico')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'db_table': 'historial_adjunto',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
