# Generated by Django 5.2.6 on 2026-04-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('nit', models.CharField(blank=True, default='', max_length=50, verbose_name='NIT')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección')),
                ('contacto', models.CharField(blank=True, default='', max_length=100, verbose_name='Persona de contacto')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores_proveedor',
                'ordering': ['nombre'],
            },
        ),
    ]
